name: Background Worker

# Run every 5 minutes
on:
  schedule:
    - cron: "*/2 * * * *"
  workflow_dispatch: # allows manual run

jobs:
  run-worker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run worker
        run: node index.mjs
